#!/bin/bash

for file in ff*;
do
year=$(head -1 $file | cut -d"-" -f1)
month=$(head -1 $file | cut -d"-" -f2)
date=$(head -1 $file | cut -d"-" -f3)

if [ -d $year ]
then
  mv $file $year
  cd $year
  if [ -d $month ]
  then
    mv $file $month
  else
    mkdir $month
    mv $file $month
  fi

  cd $month
  if [ -d $date ]
  then
    mv $file $date
  else
    mkdir $date
    mv $file $date
  fi

else
  mkdir $year
  mv $file $year
  cd $year
  if [ -d $month ]
  then
    mv $file $month
  else
    mkdir $month
    mv $file $month
  fi

  cd $month
  if [ -d $date ]
  then
    mv $file $date
  else
    mkdir $date
    mv $file $date
  fi
fi
cd ..
